### ISSUE TITLE
Unexpected behavior on Windows, when cwd is relative

### ISSUE THREAD

**Issue by vallentin** [magiclen/path-dedot#8]
Note, that I encountered this behavior on Windows, but have not tested other platforms.

```rust
let p = Path::new("../abc").parse_dot_from(Path::new("C:\\foo\\bar\\baz")).unwrap();
let p = Path::new("../abc").parse_dot_from(Path::new("C:/foo/bar/baz")).unwrap();

let p = Path::new("..\\abc").parse_dot_from(Path::new("C:\\foo\\bar\\baz")).unwrap();
let p = Path::new("..\\abc").parse_dot_from(Path::new("C:/foo/bar/baz")).unwrap();
```

All the above `p` resolve into `"C:\\foo\\bar\\abc"`, which is expected.

However, the following resolve unexpectedly:

```rust
let p = Path::new("../abc").parse_dot_from(Path::new("foo\\bar\\baz")).unwrap();
let p = Path::new("../abc").parse_dot_from(Path::new("foo/bar/baz")).unwrap();

let p = Path::new("..\\abc").parse_dot_from(Path::new("foo\\bar\\baz")).unwrap();
let p = Path::new("..\\abc").parse_dot_from(Path::new("foo/bar/baz")).unwrap();
```

All the above `p` resolve into `"foobarabc"`, where `"foo/bar/abc"` or `"foo\\bar\\abc"` would instead be expected.

**Comment by magiclen** [comment]
I never thought anyone would use it in this way.

**Comment by magiclen** [comment]
It should be fixed now. [`path-absolutize`](https://github.com/magiclen/path-absolutize) also has this issue, and it's fixed as well.

**Comment by vallentin** [comment]
Thanks a lot!

I can confirm, that the expected behavior is produced by both `parse_dot_from()` and `absolutize_from()`.

Now looking at `path_absolutize`. I thought maybe `absolutize_virtually()` was what I actually needed. As my paths might not exist. However, with the same initial examples. Using `absolutize_virtually()` seems to error with `InvalidInput`. Not sure if that's intended or not, in these cases, since I didn't look much into the differences.

Regardless, my issue has been fixed. So again, thanks!

**Comment by magiclen** [comment]
```rust
path.absolutize_virtually(virtual_root).unwrap();
```

The `path` must under `virtual_root` or you will get an `InvalidInput` error.

### Examples

```rust
Path::new("abc").absolutize_virtually("/foo/bar"); // ok
Path::new("/abc").absolutize_virtually("/foo/bar"); // err
Path::new("./abc").absolutize_virtually("/foo/bar"); // err, because the cwd is not `/foo/bar`
Path::new("../abc").absolutize_virtually("/foo/bar"); // err, because the cwd is not `/foo/bar/xxx`
```

**Comment by vallentin** [comment]
I'm still not quire sure I understand the difference. So in `absolutize_virtually()`, when the path is resolved, if the absolute path, does not have `virtual_root` as its root, then it errors?

At least that's my quick interpretation of the [`absolutize_virtually()` tests](https://github.com/magiclen/path-absolutize/blob/master/tests/unix.rs#L222-L260). Though, if that is true, then I'm not sure why the third case in your example fails.

Regardless. You fixed my previous issue, so thanks again!

**Comment by magiclen** [comment]
If the cwd is `/home/user`, `./abc` is actual `/home/user/abc` which is not under `/foo/bar`. Thus, the error occurs.
